---
# Inventory for when we run Ansible directly (i.e., not via Vagrant)

epic: # This creates the first epic node
  hosts:
    epic1: # the first epic host in a multinode cluster
      ws_hostname: epic1-ctl
      k8s_nic: enp1s0
      ansible_user: install_user

epicnode: # this creates additional nodes in the epic cluster
  hosts:
    epic2:
      k8s_nodeaddr: 192.168.254.12
      join_script: join-epic-cluster
      admin_conf: epic-admin.conf
    epic3:
      k8s_nodeaddr: 192.168.254.13
      join_script: join-epic-cluster
      admin_conf: epic-admin.conf


client: # these scripts will create a client cluster with the epic gateway controllers installed
  hosts:
    mk8s1: # the first client host in a multinode cluster
      k8s_nodeaddr: 192.168.254.101,fd00:254::101
node:
  hosts:
    mk8s2:
      k8s_nodeaddr: 192.168.254.102,fd00:254::102
    mk8s3:
      k8s_nodeaddr: 192.168.254.103,fd00:254::103
