---
# Inventory for when we run Ansible directly (i.e., not via Vagrant)

epic:
  hosts:
    epic1: # the first epic host in an acndev cluster, usually 192.168.254.11
      k8s_cluster_vip: 192.168.254.11
      true_ingress_interface: eth1
      ws_hostname: acndev-ctl

    192.168.10.50:
      ansible_user: adamd
      k8s_nic: ens4
      k8s_cluster_vip: 192.168.10.25
epicnode:
  hosts:
    epic2:
      k8s_nodeaddr: 192.168.254.12
      join_script: join-epic-cluster
      admin_conf: epic-admin.conf
    epic3:
      k8s_nodeaddr: 192.168.254.13
      join_script: join-epic-cluster
      admin_conf: epic-admin.conf
client:
  hosts:
    mk8s1: # the first client host in a multinode cluster, usually 192.168.254.101,fd00:254::101
      k8s_cluster_vip: 192.168.254.101
      k8s_nodeaddr: 192.168.254.101,fd00:254::101
node:
  hosts:
    mk8s2:
      k8s_nodeaddr: 192.168.254.102,fd00:254::102
    mk8s3:
      k8s_nodeaddr: 192.168.254.103,fd00:254::103
