
$fixsysconf = <<-SCRIPT

sed -i '/net.ipv6.conf.all.disable_ipv6/d' /etc/sysctl.conf
sed -i 's/^#net.ipv4.ip_forward/net.ipv4.ip_forward/' /etc/sysctl.conf
sed -i 's/^#net.ipv6.conf.all.forwarding/net.ipv6.conf.all.forwarding/' /etc/sysctl.conf

sysctl -p /etc/sysctl.conf

SCRIPT

$installmk8s = <<-SCRIPT

snap install microk8s --classic
usermod -a -G microk8s vagrant
chown -f -R vagrant ~/.kube
microk8s status --wait-ready
microk8s enable dns
microk8s enable rbac

SCRIPT



Vagrant.configure("2") do |config|

BRIDGE = "#{ENV['USER']}" + "-epic0"


  config.vm.define 'router' do |router|
    router.trigger.before :up do |uptrigger|
      uptrigger.info = "running before up"
      uptrigger.run = {inline: "/usr/local/bin/brmgr.sh up" }
    end
    router.trigger.after :destroy do |destroytrigger|
      destroytrigger.info = "running after destroy"
      destroytrigger.run = {inline: "/usr/local/bin/brmgr.sh destroy"}
    end
    router.vm.hostname = 'router'
    router.vm.box = "frrouter"
    router.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.1"
    router.vm.network :public_network,
      :dev => "brint0",
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      use_dhcp_assigned_default_route: true
    
    router.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 2048
    end
    router.vm.provision "shell", inline: $fixsysconf
    router.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"
    

  end
 
  config.vm.define 'epic1' do |epic1|
    epic1.vm.hostname = 'epic1'
    epic1.vm.box = "generic/ubuntu2004"
    epic1.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.11"

    epic1.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 6148
    end
    epic1.vm.provision "shell", inline: $fixsysconf
    epic1.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    epic1.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"
  end

  config.vm.define 'epic2' do |epic2|
    epic2.vm.hostname = 'epic2'
    epic2.vm.box = "generic/ubuntu2004"
    epic2.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.12"

    epic2.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 6148
    end
    epic2.vm.provision "shell", inline: $fixsysconf
    epic2.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    epic2.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"
  end

  config.vm.define 'epic3' do |epic3|
    epic3.vm.hostname = 'epic3'
    epic3.vm.box = "generic/ubuntu2004"
    epic3.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.13"

    epic3.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 6148
    end
    epic3.vm.provision "shell", inline: $fixsysconf
    epic3.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    epic3.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"
  end

  config.vm.define 'mk8s1' do |mk8s1|
    mk8s1.vm.hostname = 'mk8s1'
    mk8s1.vm.box = "generic/ubuntu2004"
    mk8s1.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.101"

    mk8s1.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 4096
    end
    mk8s1.vm.provision "shell", inline: $fixsysconf
    mk8s1.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    mk8s1.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"

    mk8s1.vm.provision "shell", inline: $installmk8s

    mk8s1.vm.provision "file", source: "../scripts/kubens", destination: "kubens"
    mk8s1.vm.provision "shell", inline: "mv kubens /usr/local/bin"

    mk8s1.vm.provision "file", source: "../scripts/bash_aliases", destination: ".bash_aliases" 
    
    
  end

  config.vm.define 'mk8s2' do |mk8s2|
    mk8s2.vm.hostname = 'mk8s2'
    mk8s2.vm.box = "generic/ubuntu2004"
    mk8s2.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.102"

    mk8s2.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 4096
    end
    mk8s2.vm.provision "shell", inline: $fixsysconf
    mk8s2.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    mk8s2.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"

    mk8s2.vm.provision "shell", inline: $installmk8s

    mk8s2.vm.provision "file", source: "../scripts/kubens", destination: "kubens"
    mk8s2.vm.provision "shell", inline: "mv kubens /usr/local/bin"

    mk8s2.vm.provision "file", source: "../scripts/bash_aliases", destination: ".bash_aliases" 
  
  end
  
  config.vm.define 'mk8s3' do |mk8s3|
    mk8s3.vm.hostname = 'mk8s3'
    mk8s3.vm.box = "generic/ubuntu2004"
    mk8s3.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.103"

    mk8s3.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 4096
    end
    mk8s3.vm.provision "shell", inline: $fixsysconf
    mk8s3.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    mk8s3.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"

    mk8s3.vm.provision "shell", inline: $installmk8s

    mk8s3.vm.provision "file", source: "../scripts/kubens", destination: "kubens"
    mk8s3.vm.provision "shell", inline: "mv kubens /usr/local/bin"

    mk8s3.vm.provision "file", source: "../scripts/bash_aliases", destination: ".bash_aliases" 
    
  end

 
end
