---
- name: Install the SIG Gateway APIs
  command: "kubectl apply -f {{ gw_api_artifact }}"

- name: Install the EPIC PureGW client (the version with the dev/test hostnames)
  command: "kubectl apply -f {{ gw_epic_artifact }}"
  retries: 2
  delay: 10
  register: result
  until: result is not failed

- name: Poll the web service to make sure that it's alive
  command: curl --insecure -s -o /dev/null -w "%{http_code}" https://gwdev-ctl/api/epic
  register: result
  until: result.stdout == '401'
  retries: 36
  delay: 10

- name: Wait for the epic playbook to write the sample GatewayClassConfig
  local_action:
    module: wait_for
    path: "{{ sample_gw_config }}"
- name: Upload the sample GatewayClassConfig
  template:
    src: "{{ sample_gw_config }}"
    dest: "{{ sample_gw_config }}"
- name: Apply the sample GatewayClassConfig
  command: "kubectl apply -f {{ sample_gw_config }}"
  retries: 2
  delay: 10
  register: result
  until: result is not failed
