---
ansible_user: vagrant

k8s_nic: eth1

# optional private registry (for development)
private_registry: "{{ lookup('env', 'EPIC_PRIVATE_REGISTRY') }}"

k8s_version: 1.23.5
k8s_version_apt: "{{ k8s_version }}-00"
k8s_version_kubeadm: "v{{ k8s_version }}"

# TRUE_INGRESS config
true_ingress_remote_path: /opt/acnodal/bin
true_ingress_interface: "{{ lookup('env', 'EPIC_TRUE_INGRESS_INTF') | default('enp1s0', True) }}"
