---
# optional private registry (for development)
private_registry: "{{ lookup('env', 'EPIC_PRIVATE_REGISTRY') }}"

# kubeadm init parameters
pod_cidr: "172.20.0.0/16,fd01::/60"
svc_cidr: "172.21.0.0/16,fd02::/112"

# flannel configuration
cni_network: "172.20.0.0/16"
cni_IPv6network: "fd01::/60"

# ServicePrefix values
service_prefix_name: default
service_prefix_subnet: 192.168.77.0/24
service_prefix_pool: 192.168.77.2-192.168.77.77
service_prefix_aggregation: "/32"

# PureLB values
purelb_subnet: 192.168.254.0/24
purelb_pool: 192.168.254.200-192.168.254.201
purelb_aggregation: "/32"

# LBServiceGroup values
group_org_name: root
group_org_ns: "epic-{{ group_org_name }}"

# public artifacts
contour_chart: contour-7.0.6.tgz
contour_artifact: https://charts.bitnami.com/bitnami/{{ contour_chart }}

join_script: join-epic-cluster
admin_conf: epic-admin.conf
