
$fixsysconf = <<-SCRIPT

sed -i '/net.ipv6.conf.all.disable_ipv6/d' /etc/sysctl.conf
sed -i 's/^#net.ipv4.ip_forward/net.ipv4.ip_forward/' /etc/sysctl.conf
sed -i 's/^#net.ipv6.conf.all.forwarding/net.ipv6.conf.all.forwarding/' /etc/sysctl.conf

sysctl -p /etc/sysctl.conf

SCRIPT

$installmk8s = <<-SCRIPT

snap install microk8s --classic
usermod -a -G microk8s vagrant
chown -f -R vagrant ~/.kube
microk8s status --wait-ready
microk8s enable dns
microk8s enable rbac

SCRIPT



Vagrant.configure("2") do |config|

BRIDGE = "#{ENV['USER']}" + "-epic0"


  config.vm.define 'router' do |router|
    router.trigger.before :up do |uptrigger|
      uptrigger.info = "running before up"
      uptrigger.run = {inline: "/usr/local/bin/brmgr.sh up" }
    end
    router.trigger.after :destroy do |destroytrigger|
      destroytrigger.info = "running after destroy"
      destroytrigger.run = {inline: "/usr/local/bin/brmgr.sh destroy"}
    end
    router.vm.hostname = 'router'
    router.vm.box = "frrouter"
    router.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.1"
    router.vm.network :public_network,
      :dev => "brtest0",
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      use_dhcp_assigned_default_route: true
    
    router.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 2048
    end
    router.vm.provision "shell", inline: $fixsysconf
    router.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"
    

  end
 
  config.vm.define 'epic' do |epic|
    epic.vm.hostname = 'epic'
    epic.vm.box = "generic/ubuntu2004"
    epic.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.10"

    epic.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 6148
    end
    epic.vm.provision "shell", inline: $fixsysconf
    epic.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    epic.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"
  end

  config.vm.define 'mk8s' do |mk8s|
    mk8s.vm.hostname = 'mk8s'
    mk8s.vm.box = "generic/ubuntu2004"
    mk8s.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.100"

    mk8s.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 4096
    end
    mk8s.vm.provision "shell", inline: $fixsysconf
    mk8s.vm.provision "shell",
      run: "always",
      inline: "ip route add default via 192.168.254.1"
    mk8s.vm.provision "shell",
      run: "always",
      inline: "ip route del default dev eth0"

    mk8s.vm.provision "shell", inline: $installmk8s

    mk8s.vm.provision "file", source: "../scripts/kubens", destination: "kubens"
    mk8s.vm.provision "shell", inline: "mv kubens /usr/local/bin"

    mk8s.vm.provision "file", source: "../scripts/bash_aliases", destination: ".bash_aliases" 
    
    
  end

 
end
