# Vagrantfile for a simple demo environment.
#
# 2 virtual machines:
#  * "gateway" is a single-node k8s cluster running the epic gateway host
#  * "gwclient" is a single-node k8s cluster running the gateway-api client

BRIDGE = "#{ENV['USER']}-epic0"
WEB_SERVICE = 'gwdev-ctl'
PLAYBOOK = '../playbook/site.yml'
GROUPS = {
  epic: ['gateway'],
  client: ['gwclient']
}

Vagrant.configure("2") do |config|

  config.vm.box = 'generic/ubuntu2004'

  config.vm.define :gateway do |vm|
    vm.vm.hostname = 'epic-gateway.localdomain'
    vm.vm.network :public_network,
                  dev: BRIDGE,
                  ip: "192.168.254.21"

    vm.vm.provider :libvirt do |lv|
      lv.cpus = 4
      lv.memory = 6148
    end

    vm.vm.provision 'ansible' do |ansible|
      ansible.playbook = PLAYBOOK
      ansible.groups = GROUPS
      ansible.extra_vars = {
        purelb_pool: '192.168.254.210-192.168.254.211',
        ws_hostname: WEB_SERVICE
      }
    end
  end

  config.vm.define :gwclient do |vm|
    vm.vm.hostname = 'epic-client.localdomain'
    vm.vm.network :public_network,
                  dev: BRIDGE,
                  ip: "192.168.254.121"

    vm.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 4096
    end

    vm.vm.provision 'ansible' do |ansible|
      ansible.playbook = PLAYBOOK
      ansible.groups = GROUPS
      ansible.extra_vars = {
        k8s_cluster_vip: '192.168.254.121',
        k8s_nodeaddr: '192.168.254.121,fd00:254::121',
        ws_hostname: WEB_SERVICE
      }
    end
  end

end
