
$fixsysconf = <<-SCRIPT
sed -i '/net.ipv6.conf.all.disable_ipv6/d' /etc/sysctl.conf
sed -i 's/^#net.ipv4.ip_forward/net.ipv4.ip_forward/' /etc/sysctl.conf
sed -i 's/^#net.ipv6.conf.all.forwarding/net.ipv6.conf.all.forwarding/' /etc/sysctl.conf
sed -i 's/^#net.ipv4.conf.all.log_martians/net.ipv4.conf.all.log_martians/' /etc/sysctl.conf
sysctl -p /etc/sysctl.conf
SCRIPT

$deleth0dhcpdefault = <<-SCRIPT
sed -i '/^[[:space:]]*dhcp4:[[:space:]]true/a \\     \\ dhcp4-overrides:' /etc/netplan/01-netcfg.yaml
sed -i '/^[[:space:]]*dhcp4-overrides:/a \\       \\ use-routes: false'  /etc/netplan/01-netcfg.yaml 
SCRIPT

$fixhosts = <<-SCRIPT
sed -i '/ubuntu2004/d' /etc/hosts
sed -i 's/^127.0.2.1/127.0.1.1/' /etc/hosts
SCRIPT

$routerasdefault = <<-SCRIPT
sed -i  '$ a \\     \\ gateway4: 192.168.254.1' /etc/netplan/50-vagrant.yaml
SCRIPT

$installmk8s = <<-SCRIPT
snap install microk8s --classic --channel=1.22/stable
usermod -a -G microk8s vagrant
chown -f -R vagrant ~/.kube
microk8s status --wait-ready
microk8s enable dns
microk8s enable rbac
SCRIPT


Vagrant.configure("2") do |config|

BRIDGE = "#{ENV['USER']}" + "-epic0"


  config.vm.define 'router' do |router|
    router.trigger.before :up do |uptrigger|
      uptrigger.info = "running before up"
      uptrigger.run = {inline: "/usr/local/bin/brmgr.sh up" }
    end
    router.trigger.after :destroy do |destroytrigger|
      destroytrigger.info = "running after destroy"
      destroytrigger.run = {inline: "/usr/local/bin/brmgr.sh destroy"}
    end
    router.vm.hostname = 'router'
    router.vm.box = "frrouter"
    router.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      auto_config: false
    router.vm.network :public_network,
      :dev => "brint0",
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      auto_config: false
    
    router.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 2048
      lv.storage_pool_name = "lv-vmdisks"
    end
    router.vm.provision "shell", inline: $fixsysconf
    router.vm.provision "shell", inline: $fixhosts
    router.vm.provision "shell", inline: $deleth0dhcpdefault
    router.vm.provision "shell", inline: "netplan apply"  
  end
 
  config.vm.define 'epic' do |epic|
    epic.vm.hostname = 'epic'
    epic.vm.box = "generic/ubuntu2004"
    epic.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.10"

    epic.vm.provider :libvirt do |lv|
      lv.cpus = 4
      lv.memory = 6148
      lv.storage_pool_name = "lv-vmdisks"
    end
    epic.vm.provision "shell", inline: $fixsysconf
    epic.vm.provision "shell", inline: $fixhosts
    epic.vm.provision "shell", inline: $deleth0dhcpdefault
    epic.vm.provision "shell", inline: $routerasdefault
    epic.vm.provision "shell", inline: "netplan apply"
  end

  config.vm.define 'mk8s' do |mk8s|
    mk8s.vm.hostname = 'mk8s'
    mk8s.vm.box = "generic/ubuntu2004"
    mk8s.vm.network :public_network, 
      :dev => BRIDGE,
      :mode => "bridge",
      :type => "bridge",
      :trust_guest_rx_filters => "true",
      ip: "192.168.254.100"

    mk8s.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 4096
      lv.storage_pool_name = "lv-vmdisks"
    end
    mk8s.vm.provision "shell", inline: $fixsysconf
    mk8s.vm.provision "shell", inline: $fixhosts
    mk8s.vm.provision "shell", inline: $deleth0dhcpdefault
    mk8s.vm.provision "shell", inline: $routerasdefault
    mk8s.vm.provision "shell", inline: "netplan apply"
    

    mk8s.vm.provision "shell", inline: $installmk8s

    mk8s.vm.provision "file", source: "../files/kubens", destination: "kubens"
    mk8s.vm.provision "shell", inline: "mv kubens /usr/local/bin"

    mk8s.vm.provision "file", source: "../files/bash_aliases", destination: ".bash_aliases" 
    
  
    
  end

 
end
