apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: router
    app.kubernetes.io/name: epic
  name: router
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: router
    app.kubernetes.io/name: epic
  name: bird-epic
  namespace: router
spec:
  selector:
    matchLabels:
      app: bird-epic
      app.kubernetes.io/component: router
      app.kubernetes.io/name: epic
  template:
    metadata:
      labels:
        app: bird-epic
        app.kubernetes.io/component: router
        app.kubernetes.io/name: epic
    spec:
      containers:
      - env:
        - name: BIRD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: BIRD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BIRD_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/epic-gateway/router:v2.0.8-epic0
        imagePullPolicy: Always
        name: bird-epic
        resources:
          limits:
            memory: 250Mi
          requests:
            memory: 250Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        volumeMounts:
        - mountPath: /usr/local/include/bird
          name: birdconfig
        - mountPath: /usr/local/etc
          name: bird-cm
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostNetwork: true
      volumes:
      - hostPath:
          path: /opt/acnodal/bird
          type: Directory
        name: birdconfig
      - configMap:
          name: bird-cm
        name: bird-cm
