---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epic:gwsm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - list
- apiGroups:
  - epic.acnodal.io
  resources:
  - accounts
  - epics
  - gwproxies
  - gwroutes
  - gwendpointslices
  - lbservicegroups
  - serviceprefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - accounts
  - epics
  - gwproxies
  - gwroutes
  - gwendpointslices
  - lbservicegroups
  - serviceprefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - accounts/status
  - epics/status
  - gwproxies/status
  - gwroutes/status
  - gwendpointslices/status
  - lbservicegroups/status
  - serviceprefixes/status
  verbs:
  - get
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfig
  - envoyconfigrevisions
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: epic:gwsm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: epic:gwsm
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: epic:gwsm
